### PR TITLE
Add Display and DisplayElement classes

### PR DESCRIPTION
**Pull request by Atrixsanna**
step in the direction of solving issue #4

### CODE REVIEW

**Comment by Atrixsanna** [comment]
closes #8 because the new BoardPosition now maps the battlefield coordinates to an object in a dictionary

**Comment by Atrixsanna** [comment]
closes #4 because the functionality has been added in this pull request

**Comment by Isoldhe** [comment]
You're going so fast 😅 Leave some for me 😆 I'll probably be able to do something this weekend.

**Comment by Atrixsanna** [comment]
> You're going so fast 😅 Leave some for me 😆 I'll probably be able to do something this weekend.

Hehehe, don't worry, plenty issues to solve and more to come. Every feature is a new challenge 😄 
I'm mostly trying to lay a good concrete slab of groundwork here and part of all this is actually also still figuring out how to properly handle console input and output - I'm learning too 😉 

Do you wish to further review this pull request or can it be merged?

**Comment by Isoldhe** [comment]
I think it looks good 👍 you can merge it.

**Pull request merged**
